### ISSUE TITLE
动画实现

### ISSUE THREAD

**Issue by HaoranZing** [Yuuikic/LyricsPoster#2]
请问进入网页是的动画是如何实现的呀！

**Comment by Yuuikic** [comment]
使用了[anime.js](https://animejs.com/)来实现对SVG样式的控制。包括了利用[Time Line](https://animejs.com/documentation/#timelineBasics)进行动画顺序控制，使用[SVG Line Drawing](https://animejs.com/documentation/#lineDrawing)来实现描边动画，以及对SVG元素的`fill`和`stroke-width`属性进行修改。
对应的源代码在v2分支的/src/App.vue文件中。
